apiVersion: v1
kind: Service
metadata:
  name: server-php
  labels:
    app: server-php
spec:
  type: ClusterIP
  selector:
    app: php
  ports:
  - port: 8000
    protocol: TCP
    targetPort: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-php
  labels:
    app: php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - image: php-gym:latest
        name: php
        imagePullPolicy: IfNotPresent
        command:
            - server
        ports: 
          - name: http-server
            containerPort: 8000